import 'nextra-theme-blog/style.css'
import '@/styles/globals.css'
import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import Dock from "@/entities/dock/Dock";
import { Layout } from "nextra-theme-blog";



const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`mdl-js ${ibmPlexMono.variable}`}>
      <body
        className="antialiased"
        suppressHydrationWarning
      >
        <Layout>
          <div className="min-h-screen flex flex-col justify-between">
            {children}
            <Dock />
          </div>
        </Layout>
      </body>
    </html>
  );
}
